; PlatformIO Project Configuration File
;
; ESP32 SWD Bit-Bang Programmer for STM32U585

[env:denky32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
